services:
  fastapi:
    container_name: statistics-fastapi
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - stats_network
    env_file:
      - .env.dev
    volumes:
      - fastapi_volume:/microservice
  consumer:
    container_name: statistics-consumer
    build:
      context: .
    entrypoint: /microservice/entrypoint.sh
    networks:
      - stats_network
    volumes:
      - consumer_volume:/microservice
  dynamodb:
    container_name: statistics-dynamodb
    image: amazon/dynamodb-local
    restart: unless-stopped
    ports:
      - "8002:8002"
    networks:
      - stats_network
    volumes:
      - dynamodb_volume:/home/dynamodb/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb/data/ -port 8002"
    user: root
  dynamodb-admin:
    container_name: statistics-dynamodb-admin
    image: aaronshaf/dynamodb-admin
    build:
      context: .
      dockerfile: admin.Dockerfile
    ports:
      - "8001:8001"
    networks:
      - stats_network
    env_file:
      - .env.dev
    depends_on:
      - dynamodb

volumes:
  fastapi_volume:
  dynamodb_volume:
  consumer_volume:

networks:
  stats_network:
    external:
      name: innotter_innotter_network
