services:
  fastapi:
    container_name: innotter-fastapi
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - innotter_network
    env_file:
      - .env.dev
    volumes:
      - fastapi_volume:/app

  dynamodb:
    container_name: statistics-dynamodb
    image: amazon/dynamodb-local
    restart: unless-stopped
    networks:
      - innotter_network
    ports:
      - "8002:8002"
    volumes:
      - dynamodb_volume:/home/dynamodb/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb/data/ -port 8002"
    user: root

  dynamodb-admin:
    container_name: statistics-dynamodb-admin
    image: aaronshaf/dynamodb-admin
    build:
      context: .
      dockerfile: admin.Dockerfile
    networks:
      - innotter_network
    ports:
      - "8001:8001"
    user: root
    env_file:
      - .env.dev
    depends_on:
      - dynamodb

volumes:
  fastapi_volume:
  dynamodb_volume:

networks:
  innotter_network: